apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
      app: jenkins
  ports:
    - name: http
      nodePort: 8888
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort

